const newsData = [
    // FILA 1
    { fecha: "04 de febrero 2025", resumen: "Arancel del 10% a todas las importaciones provenientes de China.", fila: 1 },
    { fecha: "04 de marzo 2025", resumen: "Arancel del 25% a las importaciones de México y Canadá, con una tasa menor para energía. 10% adicional a las importaciones de China (20%).", fila: 1 },
    { fecha: "12 de marzo 2025", resumen: "Arancel del 25% sobre el aluminio y el acero a nivel mundial.", fila: 1 },
    { fecha: "02 de abril 2025", resumen: "Anuncio de aranceles recíprocos a nivel global, con una tarifa mínima del 10%, a partir del 5 de abril. Entran en vigor los aranceles del 25% a las importaciones desde Canadá y México.", fila: 1 },
    { fecha: "09 de abril 2025", resumen: "Excepción durante 90 días, de los aranceles recíprocos (10% a la mayoría de países excepto China). Arancel de 145% a China.", fila: 1 },
    { fecha: "08 de mayo 2025", resumen: "EE. UU. y Reino Unido hacen un acuerdo para bajar aranceles; autos bajan de 27.5% a 10%, acero y aluminio de 25% a 0%, etanol baja 19% y carne entra con cuota libre.", fila: 1 },
    { fecha: "12 de mayo 2025", resumen: "EE. UU. y China acuerdan bajar tarifas por 90 días: EE. UU. reduce del 145% al 30% y China baja del 125% al 10%.", fila: 1 },
    { fecha: "10 de junio 2025", resumen: "EE. UU. y China acuerdan arancel de 55 % a productos chinos, 10 % de China a EE. UU., y fin a restricciones chinas sobre metales raros.", fila: 1 },
    { fecha: "27 de junio 2025", resumen: "EE. UU. y China pactaron el fin del embargo chino a metales raros, impuesto en abril por aranceles de EE. UU.; China reanudará exportaciones y agilizará licencias.", fila: 1 },
    { fecha: "07 de julio 2025", resumen: "EE. UU. aplaza aranceles recíprocos a 60 países hasta el 1 de agosto.", fila: 1 },

    // FILA 2
    { fecha: "08 de julio 2025", resumen: "Anuncio de nuevo arancel de 50 % a importaciones de cobre por motivos de seguridad nacional.", fila: 2 },
    { fecha: "27 de julio 2025", resumen: "Pacto de arancel del 15 % a las importaciones desde la UE a cambio de inversiones y compras en EE. UU.", fila: 2 },
    { fecha: "31 de julio 2025", resumen: "Tarifas del 10 % al 41 % desde el 7 de agosto a 69 países; 10 % para Guatemala, 15 % para la UE y 35 % para Canadá. Prórroga hasta el 29 de octubre al arancel del 30 % para México. Fin de exención arancelaria a importaciones menores de 800 USD a partir del 29 de agosto.", fila: 2 },
    { fecha: "05 de agosto 2025", resumen: "Anuncio de arancel progresivo a productos farmacéuticos, con meta de 150 % en 18 meses y 250 % a dos años.", fila: 2 },
    { fecha: "12 de agosto 2025", resumen: "Extensión de 90 días a la tregua comercial entre EE.UU. y China, manteniendo los aranceles actuales. Fin de la extensión el 10 de noviembre de 2025.", fila: 2 },
    { fecha: "19 de agosto 2025", resumen: "Extensión de arancel del 50% a nuevos productos derivados de acero y aluminio, incluyendo electrodomésticos, vagones y partes de autos eléctricos.", fila: 2 },
    { fecha: "05 de septiembre 2025", resumen: "Orden ejecutiva concederá arancel 0% a más de 45 productos (metales, químicos, farmacéuticos) provenientes de aliados con acuerdos comerciales.", fila: 2 },
    { fecha: "09 de septiembre 2025", resumen: "Inicio del acuerdo con Japón que baja aranceles a autos y autopartes al 15%, como parte del pacto de inversión firmado en julio.", fila: 2 },
    { fecha: "26 de septiembre 2025", resumen: "EE.UU. anunció aranceles de 100% a medicinas patentadas, 25% a camiones pesados, 50% a gabinetes y baños y 30% a muebles tapizados, efectivos desde el 1 de octubre de 2025. La medida excluye a la UE con un tope de 15% y a empresas con fábricas en territorio estadounidense.", fila: 2 },
    { fecha: "29 de septiembre 2025", resumen: "EE.UU. fijó un arancel de 10% a madera y maderas blandas desde el 14 de octubre y confirmó que los aranceles a gabinetes, baños y muebles serán de 25% con aumento automático a 30–50% el 1 de enero de 2026 si no se alcanza un acuerdo comercial. También se anunció la amenaza de un arancel de 100% a películas producidas en el extranjero.", fila: 2 },

    // FILA 3
    { fecha: "09 de octubre 2025", resumen: "China amplía controles para exportar metales raros y tecnologías relacionadas, vigentes a partir del 8 de noviembre.", fila: 3 },
    { fecha: "10 de octubre 2025", resumen: "EE. UU. anuncia un arancel extra del 100 % a productos chinos, vigente el 1 de noviembre (carga total del 130 %), junto a controles de exportación de software y una tarifa de 46 USD/tonelada a barcos chinos. Se aplica además un 100 % a grúas portuarias ship-to-shore.", fila: 3 },
    { fecha: "25 de octubre 2025", resumen: "Aumento de 10 % en los aranceles a bienes canadienses no exentos del USMCA tras una campaña publicitaria de Ontario con mensajes contra los aranceles.", fila: 3 },
    { fecha: "30 de octubre 2025", resumen: "EE. UU. anuncia que reducirá sus aranceles sobre importaciones chinas del 57 % al 47 %, al recortar del 20 % al 10 % los gravámenes aplicados a bienes vinculados al fentanilo. China se compromete a suspender durante un año sus nuevas restricciones a la exportación de metales raros.", fila: 3 },
    { fecha: "14 de noviembre 2025", resumen: "EE. UU. elimina aranceles a más de 200 productos alimentarios importados (carne, café, frutas) para reducir la inflación en comestibles. También suprime aranceles a productos de Ecuador, Argentina, Guatemala y El Salvador, como banano, cacao y azúcar cruda, a cambio de mayor acceso para exportaciones estadounidenses.", fila: 3 },
    { fecha: "26 de noviembre 2025", resumen: "EEUU extiende por 1 año la exclusión de aranceles a 178 productos chinos (industriales y médicos). En respuesta, China suspende todos los aranceles de represalia impuestos desde marzo.", fila: 3 },
    { fecha: "01 de diciembre 2025", resumen: "EEUU y Reino Unido firmaron acuerdo para eliminar aranceles a fármacos y dispositivos médicos británicos; Reino Unido subirá 25% lo que paga por nuevos medicamentos de EEUU. EEUU bajó de 25% a 15% los aranceles a importaciones de Corea del Sur (autos, bienes industriales). También quitó aranceles a partes de aviones y limitó a 15% futuros aranceles a semiconductores y fármacos.", fila: 3 },
    { fecha: "31 de diciembre 2025", resumen: "EE. UU. aplaza por 1 año el aumento de aranceles a muebles tapizados, gabinetes de cocina y vanidades de baño. EE. UU. confirma la entrada en vigor de aranceles del 25% a importaciones desde China a baterías de litio (no EV), guantes médicos, grafito natural e imanes permanentes.", fila: 3 },
    { fecha: "08 de enero 2026", resumen: "La Presidencia de EE. UU. respaldó un proyecto de ley que permitiría imponer aranceles de hasta 500% a importaciones de países que compren petróleo ruso.", fila: 3 },
    { fecha: "12 de enero 2026", resumen: "La Presidencia de EE. UU. anunció un arancel del 25% a importaciones de países que mantengan comercio con Irán.", fila: 3 },

    // FILA 4
    { fecha: "17 de enero 2026", resumen: "La presidencia de EE. UU. anuncia que impondrá un arancel del 10 % (aumentando al 25 % el 1 de junio) a las importaciones desde ocho países europeos (Alemania, Dinamarca, Finlandia, Francia, Noruega, Países Bajos, Reino Unido y Suecia) si la Unión Europea no accede a permitir negociaciones sobre la compra de Groenlandia.", fila: 4 },
    { fecha: "21 de enero 2026", resumen: "La presidencia de EE. UU. comunica durante el Foro Económico Mundial que se alcanzó un “marco” de entendimiento con aliados de la OTAN respecto a Groenlandia, y cancela los aranceles que estaban programados.", fila: 4 },
    { fecha: "29 de enero 2026", resumen: "EE. UU. amenaza con imponer un arancel del 50 % a aeronaves canadienses y retirar su certificación por disputas regulatorias; firma acuerdo con El Salvador que elimina aranceles recíprocos en cientos de bienes; y emite orden ejecutiva que permite sancionar con aranceles a países que abastezcan petróleo a Cuba.", fila: 4 },
    { fecha: "30 de enero 2026", resumen: "EE. UU. y Guatemala firman un acuerdo que elimina aranceles para el 70.4 % de las exportaciones guatemaltecas, incluidos café, banano y textiles; Guatemala asume compromisos en facilitación comercial, propiedad intelectual y estándares laborales. Algunos productos agrícolas no tradicionales y mercancías acuícolas siguen con arancel del 10 %.", fila: 4 },
    {fecha:"3 de febrero de 2026", resumen:"La presidencia de EE.UU. activó un marco de “arancel secundario” para gravar importaciones desde terceros países que suministren petróleo a Cuba. El anuncio no fijó una tasa única, dejando el nivel y la aplicación sujetos a designaciones y pasos posteriores.", fila: 4},
    {fecha:"6 de febrero de 2026", resumen:"La presidencia de EE.UU. autorizó imponer aranceles a importaciones de cualquier país que compre bienes o servicios a Irán.\n\nEE.UU. consolidó un arancel recíproco general de 18% a India y retiró un recargo adicional de 25%.\n\nEE.UU. acordó con Argentina reducciones arancelarias recíprocas y amplió en 80,000 toneladas métricas el cupo de importación de carne bovina argentina.", fila: 4},
    {fecha:"11 de febrero de 2026", resumen:"La Cámara de Representantes de EE. UU. aprobó 219–211 una resolución para anular los aranceles de EE. UU. a Canadá impuestos bajo una declaración de emergencia nacional. Para ser efectiva, la medida aún requiere aprobación del Senado y decisión presidencial", fila: 4},
    {fecha:"12 de febrero de 2026", resumen:"Publicación de acuerdo comercial entre EE. UU. y Taiwán. Al entrar en vigor, bienes calificados tendrían arancel recíproco 0% y el resto quedaría con una tasa combinada de 15% en EE. UU., mientras Taiwán se comprometió a reducir o eliminar la mayoría de sus aranceles a bienes de EE. UU. e incluir compromisos de compras e inversión.", fila: 4},
    {fecha:"20 de febrero de 2026", resumen:"La Corte Suprema de EE. UU. falló que la IEEPA no autoriza aranceles, dejando sin base legal los gravámenes impuestos bajo esa ley y abriendo la puerta a reclamos/reembolsos.\n\nLa Presidencia de EE. UU. activó la “sección 122” (Trade Act 1974): recargo general temporal de 10% a importaciones (hasta 150 días), con excepciones y reglas de “apilamiento” con otros aranceles.", fila: 4},
    {fecha:"21 de febrero de 2026", resumen:"La Presidencia de EE. UU. incrementa el arancel bajo la “sección 122”  de 10% a 15%.", fila: 4},
];