const newsData = [
    // FILA 1
    { fecha: "04 de febrero 2025", resumen: "Arancel del 10% a todas las importaciones provenientes de China.", status: "implemented", fila: 1 },
    { fecha: "04 de marzo 2025", resumen: "Arancel del 25% a las importaciones de México y Canadá, con una tasa menor para energía. 10% adicional a las importaciones de China (20%).", status: "implemented", fila: 1 },
    { fecha: "12 de marzo 2025", resumen: "Arancel del 25% sobre el aluminio y el acero a nivel mundial.", status: "implemented", fila: 1 },
    { fecha: "02 de abril 2025", resumen: "Anuncio de aranceles recíprocos a nivel global, con una tarifa mínima del 10%, a partir del 5 de abril. Entran en vigor los aranceles del 25% a las importaciones desde Canadá y México.", status: "announced", fila: 1 },
    { fecha: "09 de abril 2025", resumen: "Excepción durante 90 días, de los aranceles recíprocos (10% a la mayoría de países excepto China). Arancel de 145% a China.", status: "implemented", fila: 1 },
    { fecha: "08 de mayo 2025", resumen: "EE. UU. y Reino Unido hacen un acuerdo para bajar aranceles; autos bajan de 27.5% a 10%, acero y aluminio de 25% a 0%, etanol baja 19% y carne entra con cuota libre.", status: "implemented", fila: 1 },
    { fecha: "12 de mayo 2025", resumen: "EE. UU. y China acuerdan bajar tarifas por 90 días: EE. UU. reduce del 145% al 30% y China baja del 125% al 10%.", status: "implemented", fila: 1 },
    { fecha: "10 de junio 2025", resumen: "EE. UU. y China acuerdan arancel de 55 % a productos chinos, 10 % de China a EE. UU., y fin a restricciones chinas sobre metales raros.", status: "implemented", fila: 1 },
    { fecha: "27 de junio 2025", resumen: "EE. UU. y China pactaron el fin del embargo chino a metales raros, impuesto en abril por aranceles de EE. UU.; China reanudará exportaciones y agilizará licencias.", status: "implemented", fila: 1 },
    { fecha: "07 de julio 2025", resumen: "EE. UU. aplaza aranceles recíprocos a 60 países hasta el 1 de agosto.", status: "implemented", fila: 1 },
    { fecha: "08 de julio 2025", resumen: "Anuncio de nuevo arancel de 50 % a importaciones de cobre por motivos de seguridad nacional.", status: "threat", fila: 1 },

    // FILA 2
    { fecha: "27 de julio 2025", resumen: "Pacto de arancel del 15 % a las importaciones desde la UE a cambio de inversiones y compras en EE. UU.", status: "implemented", fila: 2 },
    { fecha: "31 de julio 2025", resumen: "Tarifas del 10 % al 41 % desde el 7 de agosto a 69 países; 10 % para Guatemala, 15 % para la UE y 35 % para Canadá. Prórroga hasta el 29 de octubre al arancel del 30 % para México. Fin de exención arancelaria a importaciones menores de 800 USD a partir del 29 de agosto.", status: "announced", fila: 2 },
    { fecha: "05 de agosto 2025", resumen: "Anuncio de arancel progresivo a productos farmacéuticos, con meta de 150 % en 18 meses y 250 % a dos años.", status: "threat", fila: 2 },
    { fecha: "12 de agosto 2025", resumen: "Extensión de 90 días a la tregua comercial entre EE.UU. y China, manteniendo los aranceles actuales. Fin de la extensión el 10 de noviembre de 2025.", status: "implemented", fila: 2 },
    { fecha: "19 de agosto 2025", resumen: "Extensión de arancel del 50% a nuevos productos derivados de acero y aluminio, incluyendo electrodomésticos, vagones y partes de autos eléctricos.", status: "implemented", fila: 2 },
    { fecha: "05 de septiembre 2025", resumen: "Orden ejecutiva concederá arancel 0% a más de 45 productos (metales, químicos, farmacéuticos) provenientes de aliados con acuerdos comerciales.", status: "announced", fila: 2 },
    { fecha: "09 de septiembre 2025", resumen: "Inicio del acuerdo con Japón que baja aranceles a autos y autopartes al 15%, como parte del pacto de inversión firmado en julio.", status: "implemented", fila: 2 },
    { fecha: "26 de septiembre 2025", resumen: "EE.UU. anunció aranceles de 100% a medicinas patentadas, 25% a camiones pesados, 50% a gabinetes y baños y 30% a muebles tapizados, efectivos desde el 1 de octubre de 2025. La medida excluye a la UE con un tope de 15% y a empresas con fábricas en territorio estadounidense.", status: "announced", fila: 2 },
    { fecha: "29 de septiembre 2025", resumen: "EE.UU. fijó un arancel de 10% a madera y maderas blandas desde el 14 de octubre y confirmó que los aranceles a gabinetes, baños y muebles serán de 25% con aumento automático a 30–50% el 1 de enero de 2026 si no se alcanza un acuerdo comercial. También se anunció la amenaza de un arancel de 100% a películas producidas en el extranjero.", status: "threat", fila: 2 },
    { fecha: "09 de octubre 2025", resumen: "China amplía controles para exportar metales raros y tecnologías relacionadas, vigentes a partir del 8 de noviembre.", status: "announced", fila: 2 },
    { fecha: "10 de octubre 2025", resumen: "EE. UU. anuncia un arancel extra del 100 % a productos chinos, vigente el 1 de noviembre (carga total del 130 %), junto a controles de exportación de software y una tarifa de 46 USD/tonelada a barcos chinos. Se aplica además un 100 % a grúas portuarias ship-to-shore.", status: "announced", fila: 2 },
    
    // FILA 3
    { fecha: "25 de octubre 2025", resumen: "Aumento de 10 % en los aranceles a bienes canadienses no exentos del USMCA tras una campaña publicitaria de Ontario con mensajes contra los aranceles.", status: "implemented", fila: 3 },
    { fecha: "30 de octubre 2025", resumen: "EE. UU. anuncia que reducirá sus aranceles sobre importaciones chinas del 57 % al 47 %, al recortar del 20 % al 10 % los gravámenes aplicados a bienes vinculados al fentanilo. China se compromete a suspender durante un año sus nuevas restricciones a la exportación de metales raros.", status: "implemented", fila: 3 },
    { fecha: "14 de noviembre 2025", resumen: "EE. UU. elimina aranceles a más de 200 productos alimentarios importados (carne, café, frutas) para reducir la inflación en comestibles. También suprime aranceles a productos de Ecuador, Argentina, Guatemala y El Salvador, como banano, cacao y azúcar cruda, a cambio de mayor acceso para exportaciones estadounidenses.", status: "implemented", fila: 3 },
    { fecha: "26 de noviembre 2025", resumen: "EEUU extiende por 1 año la exclusión de aranceles a 178 productos chinos (industriales y médicos). En respuesta, China suspende todos los aranceles de represalia impuestos desde marzo.", status: "implemented", fila: 3 },
    { fecha: "01 de diciembre 2025", resumen: "EEUU y Reino Unido firmaron acuerdo para eliminar aranceles a fármacos y dispositivos médicos británicos; Reino Unido subirá 25% lo que paga por nuevos medicamentos de EEUU. EEUU bajó de 25% a 15% los aranceles a importaciones de Corea del Sur (autos, bienes industriales). También quitó aranceles a partes de aviones y limitó a 15% futuros aranceles a semiconductores y fármacos.", status: "implemented", fila: 3 },
    { fecha: "31 de diciembre 2025", resumen: "EE. UU. aplaza por 1 año el aumento de aranceles a muebles tapizados, gabinetes de cocina y vanidades de baño. EE. UU. confirma la entrada en vigor de aranceles del 25% a importaciones desde China a baterías de litio (no EV), guantes médicos, grafito natural e imanes permanentes.", status: "implemented", fila: 3 },
    { fecha: "08 de enero 2026", resumen: "La Presidencia de EE. UU. respaldó un proyecto de ley que permitiría imponer aranceles de hasta 500% a importaciones de países que compren petróleo ruso.", status: "threat", fila: 3 },
    { fecha: "12 de enero 2026", resumen: "La Presidencia de EE. UU. anunció un arancel del 25% a importaciones de países que mantengan comercio con Irán.", status: "threat", fila: 3 },
    { fecha: "17 de enero 2026", resumen: "La presidencia de EE. UU. anuncia que impondrá un arancel del 10 % (aumentando al 25 % el 1 de junio) a las importaciones desde ocho países europeos (Alemania, Dinamarca, Finlandia, Francia, Noruega, Países Bajos, Reino Unido y Suecia) si la Unión Europea no accede a permitir negociaciones sobre la compra de Groenlandia.", status: "threat", fila: 3 },
    { fecha: "21 de enero 2026", resumen: "La presidencia de EE. UU. comunica durante el Foro Económico Mundial que se alcanzó un “marco” de entendimiento con aliados de la OTAN respecto a Groenlandia, y cancela los aranceles que estaban programados.", status: "implemented", fila: 3 },
    { fecha: "29 de enero 2026", resumen: "EE. UU. amenaza con imponer un arancel del 50 % a aeronaves canadienses y retirar su certificación por disputas regulatorias; firma acuerdo con El Salvador que elimina aranceles recíprocos en cientos de bienes; y emite orden ejecutiva que permite sancionar con aranceles a países que abastezcan petróleo a Cuba.", status: "threat", fila: 3 },

    // FILA 4
    { fecha: "30 de enero 2026", resumen: "EE. UU. y Guatemala firman un acuerdo que elimina aranceles para el 70.4 % de las exportaciones guatemaltecas, incluidos café, banano y textiles; Guatemala asume compromisos en facilitación comercial, propiedad intelectual y estándares laborales. Algunos productos agrícolas no tradicionales y mercancías acuícolas siguen con arancel del 10 %.", status: "implemented", fila: 4 },
    { fecha: "3 de febrero de 2026", resumen: "La presidencia de EE.UU. activó un marco de “arancel secundario” para gravar importaciones desde terceros países que suministren petróleo a Cuba. El anuncio no fijó una tasa única, dejando el nivel y la aplicación sujetos a designaciones y pasos posteriores.", status: "announced", fila: 4 },
    { fecha: "6 de febrero de 2026", resumen: "La presidencia de EE.UU. autorizó imponer aranceles a importaciones de cualquier país que compre bienes o servicios a Irán.\n\nEE.UU. consolidó un arancel recíproco general de 18% a India y retiró un recargo adicional de 25%.\n\nEE.UU. acordó con Argentina reducciones arancelarias recíprocas y amplió en 80,000 toneladas métricas el cupo de importación de carne bovina argentina.", status: "announced", fila: 4 },
    { fecha: "11 de febrero de 2026", resumen: "La Cámara de Representantes de EE. UU. aprobó 219–211 una resolución para anular los aranceles de EE. UU. a Canadá impuestos bajo una declaración de emergencia nacional. Para ser efectiva, la medida aún requiere aprobación del Senado y decisión presidencial", status: "announced", fila: 4 },
    { fecha: "12 de febrero de 2026", resumen: "Publicación de acuerdo comercial entre EE. UU. y Taiwán. Al entrar en vigor, bienes calificados tendrían arancel recíproco 0% y el resto quedaría con una tasa combinada de 15% en EE. UU., mientras Taiwán se comprometió a reducir o eliminar la mayoría de sus aranceles a bienes de EE. UU. e incluir compromisos de compras e inversión.", status: "announced", fila: 4 },
    { fecha: "20 de febrero de 2026", resumen: "La Corte Suprema de EE. UU. falló que la IEEPA no autoriza aranceles, dejando sin base legal los gravámenes impuestos bajo esa ley y abriendo la puerta a reclamos/reembolsos.\n\nLa Presidencia de EE. UU. activó la “sección 122” (Trade Act 1974): recargo general temporal de 10% a importaciones (hasta 150 días), con excepciones y reglas de “apilamiento” con otros aranceles.", status: "implemented", fila: 4 },
    { fecha: "21 de febrero de 2026", resumen: "La Presidencia de EE. UU. incrementa el arancel bajo la “sección 122”  de 10% a 15%.\n\n(Amenaza)", status: "threat", fila: 4 },
    { fecha: "24 de febrero de 2026", resumen: "La Oficina de Aduanas y Protección Fronteriza de Estados Unidos (CBP) aplica el recargo del 10% conforme a la Sección 122.", status: "implemented", fila: 4 },
    { fecha: "3 de marzo de 2026", resumen: "Un tribunal federal de apelaciones de EE. UU. no concedió la pausa solicitada por el gobierno de EE. UU. para retrasar la implementación del fallo de la Corte Suprema y ordenó que los casos regresen a la U.S. Court of International Trade (CIT) para definir los siguientes pasos. Esto agiliza el procesamiento de demandas y posibles reembolsos arancelarios.", status: "implemented", fila: 4 },
    { fecha: "2 de abril de 2026", resumen: "EE.UU. publicó proclamaciones que actualizan los aranceles de la sección 232 sobre aluminio, cobre y productos farmacéuticos. En aluminio y sus derivados, la medida entra en vigor el 6 de abril de 2026 e incluye una tasa de 200% para productos de origen ruso o con aluminio fundido o colado en Rusia; 25% para productos del Reino Unido; 50% para la mayoría de los demás productos; y 10% para ciertos derivados con al menos 95% del aluminio fundido y colado en EE.UU.\n\nEn cobre y sus artículos, la medida entra en vigor el 6 de abril de 2026 e incluye una tasa general de 50%, 25% para ciertos productos del Annex I-B y 10% para artículos con al menos 95% del cobre fundido y colado en EE.UU.\n\nEn productos farmacéuticos patentados, ingredientes farmacéuticos y derivados, la medida entra en vigor el 31 de julio de 2026 para algunas empresas y el 29 de septiembre de 2026 para otras. La tasa general es de 100% menos el arancel base, con excepciones de 0% para ciertos productos o empresas, 10% para productos del Reino Unido, 15% menos el arancel base para algunos socios y 20% para bienes sujetos a planes de relocalización productiva.", status: "announced", fila: 4 },
    { fecha: "8 de abril de 2026", resumen: "La Presidencia de EE.UU. amenaza con imponer un arancel de 50% a todas las importaciones provenientes de cualquier país que suministre armas militares a Irán. El anuncio fue realizado en Truth Social, con vigencia “inmediata”, sin exclusiones ni exenciones, y fue interpretado principalmente como una advertencia a China y Rusia.", status: "threat", fila: 4 },
    { fecha: "7 de mayo de 2026", resumen: "El Tribunal de Comercio Internacional de EE.UU. (CIT) emitió un fallo 2-1 declarando ilegal el arancel global del 10% impuesto por Trump bajo la Sección 122 de la Ley de Comercio de 1974, ordenando la devolución de aranceles con intereses a los tres demandantes (Basic Fun!, Burlap & Barrel y el Estado de Washington). El tribunal rechazó otorgar un alivio a nivel nacional, por lo que el arancel continúa cobrándose al resto de los importadores mientras la administración apela.", status: "legal_ruling", fila: 4 },
    { fecha: "02 de junio de 2026", resumen: "La presidencia de EE. UU. propone aranceles adicionales bajo la Sección 301 a 60 economías por fallas en la aplicación de leyes contra el trabajo forzado. Se propone un 10% adicional a países que tienen legislación pero no la aplican efectivamente (incluyendo Guatemala, El Salvador, Canadá, México y la Unión Europea, entre otros); y un 12.5% adicional a países que carecen de dicha legislación (incluyendo China, India y Japón, entre otros).\n\nLos bienes cubiertos por el T-MEC y los sujetos a aranceles de la Sección 232 quedan exentos. La medida aún no está en vigor y se espera una decisión final después del 7 de julio de 2026.", status: "threat", fila: 5 },
    { fecha: "08 de junio de 2026", resumen: "Entran en vigor las nuevas tasas arancelarias de la Sección 232 sobre acero, aluminio y cobre, conforme a la proclamación firmada el 1 de junio de 2026. La medida estará vigente hasta el 31 de diciembre de 2027.\n\nRespecto a maquinaria, los equipos agrícolas como cosechadoras bajan su arancel de 25% a 15%. Los montacargas y equipos similares provenientes de países con acuerdo comercial vigente con EE. UU. quedan sujetos a esa misma tasa del 15%.\n\nSobre los umbrales de contenido local, los productos fabricados con al menos un 85% de metal fundido y procesado en EE. UU. califican para una tasa reducida del 10%. Anteriormente, ese umbral era del 95%, por lo que la reducción amplía el número de productos que pueden acceder a la tasa preferencial.\n\nFinalmente, se amplía la lista de productos cubiertos para incluir nuevos derivados de aluminio y acero, como planchas para impresión y estanterías metálicas.", status: "implemented", fila: 5 },
// Entrada consolidada, 20 de julio de 2026 (Canadá y Brasil)
    { 
        fecha: "20 de julio de 2026", 
        resumen: `La Presidencia de EE. UU. firmó tres proclamaciones bajo la Sección 338 de la Ley Arancelaria de 1930, imponiendo un arancel adicional del 50% a cerca de 554 líneas arancelarias de Canadá, entre ellas automóviles, lácteos, alcohol, vino, palos de hockey y cemento. La medida entra en vigor el 19 de agosto de 2026 y aplica a los bienes cubiertos aunque califiquen como originarios bajo el T-MEC (un certificado de origen válido no exime del arancel). Quedan exentas energía, potasa, minerales críticos, pescado y bienes ya sujetos a aranceles de la Sección 232.

        [Informe de la Casa Blanca](https://www.whitehouse.gov/fact-sheets/2026/07/fact-sheet-president-donald-j-trump-imposes-additional-tariffs-on-canada/)

        El mismo día, la Oficina del Representante Comercial de EE. UU. (USTR) formalizó, mediante notificación en el Registro Federal, un arancel adicional del 25% sobre la mayoría de los productos originarios de Brasil, al concluir una investigación de la Sección 301 sobre prácticas comerciales consideradas injustificadas (comercio digital y pagos electrónicos, aranceles preferenciales, protección de propiedad intelectual, acceso al mercado de etanol y deforestación ilegal). La medida entra en vigor el 22 de julio de 2026 y afecta cerca del 18% de las exportaciones brasileñas hacia EE. UU. incluyendo acero, hierro, etanol, maquinaria, textiles, azúcar y productos agrícolas. Quedan exentos los bienes ya cubiertos por aranceles de la Sección 232 y ciertas materias primas sin oferta doméstica suficiente.

        [Registro Federal](https://www.federalregister.gov/documents/2026/07/20/2026-14542/notice-of-action-brazils-acts-policies-and-practices-related-to-digital-trade-and-electronic-payment)`, 
        status: "implemented", 
        fila: 5
    },

    // Nueva entrada, Trabajo forzado, Sección 301 (60 economías)
    { 
        fecha: "23 de julio de 2026", 
        resumen: `La Presidencia de EE. UU. instruyó a la USTR imponer aranceles bajo la Sección 301 a 60 economías por no prohibir, o no aplicar de forma efectiva, la prohibición de importaciones vinculadas a trabajo forzado. La medida entra en vigor el 24 de julio de 2026, en el mismo momento en que vence el recargo temporal de la Sección 122. Aplica un arancel adicional del 10% a economías con legislación parcial o comprometida (incluyendo Guatemala, El Salvador, Canadá y México) y del 12.5% a economías sin dicha legislación (incluyendo China, Brasil e India, entre otras); para la Unión Europea, Taiwán, Japón, Corea del Sur y Suiza, el arancel se limita para que, sumado al arancel general vigente, no supere el 10% o 12.5% según el caso. Quedan exentos los bienes que califican bajo el T-MEC, el CAFTA-DR (incluye textiles de Guatemala, El Salvador y Honduras, entre otros) y los productos ya sujetos a aranceles de la Sección 232.

        [Informe de la USTR](https://ustr.gov/about/policy-offices/press-office/press-releases/2026/july/ustr-takes-action-forced-labor-section-301-investigations)`, 
        status: "implemented", 
        fila: 5 
    },
    // Nueva entrada, Sección 232 farmacéuticos, entrada en vigor primer grupo
    { 
        fecha: "31 de julio de 2026", 
        resumen: `Entró en vigor, para el primer grupo de empresas designadas (Anexo III), el arancel de la Sección 232 sobre productos farmacéuticos patentados, ingredientes farmacéuticos activos y derivados, establecido mediante la Proclamación 11020 del 2 de abril de 2026. La tasa general es del 100% menos el arancel base, con excepciones de 0% para ciertos productos o empresas, 10% para productos del Reino Unido, 15% menos el arancel base para algunos socios (Unión Europea, Japón, Corea del Sur, Suiza) y 20% para bienes sujetos a planes de relocalización productiva. El resto de las empresas queda sujeto a la medida a partir del 29 de septiembre de 2026.

        [Proclamación 11020, Casa Blanca](https://www.whitehouse.gov/presidential-actions/2026/04/adjusting-imports-of-pharmaceuticals-and-pharmaceutical-ingredients-into-the-united-states/)`, 
        status: "implemented", 
        fila: 5 
    },
    { 
        fecha: "6 de agosto de 2026", 
        resumen: `La Presidencia de EE. UU. firmó una proclamación bajo la Sección 232 que ajusta las importaciones de polisilicio y sus derivados, tras una investigación del Departamento de Comercio que determinó una amenaza a la seguridad nacional en ese sector. La medida entra en vigor el 4 de diciembre de 2026 y combina dos mecanismos: un programa de precios mínimos de importación (21 USD por kilogramo de polisilicio, 100 USD por kilogramo de lingotes y obleas, 0.22 USD por vatio de celdas solares y 0.38 USD por vatio de módulos solares) y un arancel adicional del 15% sobre los derivados del polisilicio. Para productos de Japón, Corea del Sur, Taiwán, Suiza, Liechtenstein y la Unión Europea, el arancel de la Sección 232 se ajusta para que, sumado a la tasa general vigente, no supere el 15%; para el Reino Unido, la tasa queda en 10%. La proclamación reemplaza un arancel de salvaguardia más limitado sobre celdas y módulos solares que había expirado en febrero de 2026, e incluye un programa de incentivos para empresas que construyan nueva capacidad de producción de polisilicio, lingotes, obleas y celdas en EE. UU.

        [Proclamación, Casa Blanca](https://www.whitehouse.gov/presidential-actions/2026/08/adjusting-imports-of-polysilicon-and-its-derivatives-into-the-united-states/)`, 
            status: "implemented", 
        fila: 5 
    },
];
